
DROP TABLE IF EXISTS community;
CREATE TABLE `community` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `name` VARCHAR(50) NOT NULL COMMENT '小区名称',
    `address` VARCHAR(200) DEFAULT NULL COMMENT '小区地址',
    `region_code` VARCHAR(20) DEFAULT NULL COMMENT '区域编码',
    `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已删除: 0 否, 1 是',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1000 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '小区表';

